openapi: 3.0.3
info:
  title: Приложение такси
  description: Спецификация API для приложения такси
  version: 1.0.0
servers:
  - url: "http://127.0.0.1:5000"
    description: Тестовый сервер
components:
  schemas:
    Driver:
      description: Информация о водителе
      type: object
      properties:
        driver_id:
          description: Идентификатор
          type: integer
        driver_name:
          description: Имя водителя
          type: string
        email:
          description: Электронная почта
          type: string
        phone_number:
          description: Номер телефона
          type: string
        car_model:
          description: Модель автомобиля
          type: string
        car_license_plate:
          description: Номерной знак автомобиля
          type: string
        availability:
          description: Доступность
          type: string
        location:
          description: Местоположение такси
          type: array
          items:
            type: string
        sum_trips:
          description: Суммарное количество поездок
          type: integer
      required:
        - driver_id
        - driver_name
        - phone_number
        - car_model
        - car_license_plate
        - availability
        - location

    Trip:
      description: Информация о поездке
      type: object
      properties:
        trip_id:
          description: Идентификатор поездки
          type: integer
        user_id:
          description: Идентификатор пользователя
          type: integer
        driver_id:
          description: Идентификатор водителя
          type: integer
        pickup_location:
          description: Место начала поездки
          type: array
          items:
            type: string
        dropoff_location:
          description: Место окончания поездки
          type: array
          items:
            type: string
        start_time:
          description: Время начала поездки
          type: array
          items:
            type: number
        end_time:
          description: Время окончания поездки
          type: array
          items:
            type: number
        fare:
          description: Стоимость поездки
          type: integer
        status:
          description: Статус поездки
          type: string
      required:
        - trip_id
        - user_id
        - driver_id
        - pickup_location
        - dropoff_location
        - start_time
        - end_time
        - fare
        - status

    RegistrationForm:
      description: Информация о новом клиенте
      type: object
      properties:
        username:
          description: Имя пользователя
          type: string
        email:
          description: Электронная почта
          type: string
        password:
          description: Пароль
          type: string
      required:
        - username
        - email
        - password
    
    LoginForm:
      description: Информация о сущесвтующем клиенте
      type: object
      properties:
        email:
          description: Электронная почта
          type: string
        password:
          description: Пароль
          type: string
      required:
        - email
        - password

    ChangePasswordForm:
      description: Форма для смены пароля
      type: object
      properties:
        old_password:
          description: Текущий пароль пользователя
          type: string
        new_password:
          description: Новый пароль пользователя
          type: string
      required:
        - old_password
        - new_password

    CardForm:
      description: Форма для добавления карты
      type: object
      properties:
        card_number:
          description: Номер карты
          type: string
        card_name:
          description: Имя на карте
          type: string
        expiry_date:
          description: Срок действия
          type: string
        cvv:
          description: CVV
          type: string
      required:
        - card_number
        - card_name
        - expiry_date
        - cvv

    SelectCardForm:
      description: Форма для выбора карты
      type: object
      properties:
        card_id:
          description: Идентификатор карты
          type: integer
      required:
        - card_id


paths:
  /:
    get:
      description: Получение домашней страницы
      operationId: lokir.index
      responses:
        "200":
          description: Домашняя страница
          content:
            text/html:
              schema:
                type: string
  /register:
    post:
      description: Регистрация нового пользователя
      operationId: lokir.registration
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/RegistrationForm"
      responses:
        "200":
          description: Успешная регистрация
        "400":
          description: Неверный формат данных
        "409":
          description: Пользователь с таким адресом электронной почты уже существует
    get:
      description: Сервер возвращает HTML форму для регистрации
      operationId: lokir.registrationForm
      responses:
        "200":
          description: Форма регистрации возвращена
          content:
            text/html:
              schema:
                type: string
  /login:
    post:
      description: Авторизация пользователя
      operationId: lokir.authorization
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/LoginForm"
      responses:
        "302":
          description: Успешная авторизация
        "400":
          description: Неверный формат данных
        "401":
          description: Неверный пароль
        "404":
          description: Пользователь не найден
    get:
      description: Сервер возвращает HTML форму для авторизации
      operationId: lokir.authorizationForm
      responses:
        "200":
          description: Форма для авторизации возвращена
          content:
            text/html:
              schema:
                type: string
  /order:
    get:
      description: Сервер возвращает HTML форму для заказа
      operationId: lokir.orderGet
      responses:
        "200":
          description: Форма для заказа возвращена
          content:
            text/html:
              schema:
                type: string
        "401":
          description: Пользователь неавторизован(токен неверный или время его действия истекло)
    post:
      description: Получение данных о заказе сервером
      operationId: lokir.orderCreate
      responses:
        "200":
          description: Заказ успешно создан
        "400":
          description: Неверный формат данных
  /account:
    get:
      description: Получение информации об аккаунте авторизованного пользователя
      operationId: lokir.account
      responses:
        "200":
          description: Успешное получение информации об аккаунте
          content:
            text/html:
              schema:
                type: string
        "401":
          description: Пользователь не авторизован
  /logout:
    get:
      description: Выход из аккаунта авторизованного пользователя
      operationId: lokir.logout
      responses:
        "302":
          description: Успешный выход из аккаунта
          headers:
            Location:
              schema:
                type: string
              description: URL для перенаправления после выхода
        "401":
          description: Пользователь не авторизован
  /change_password:
    get:
      description: Получение формы для смены пароля авторизованного пользователя
      operationId: lokir.changePasswordGet
      responses:
        "200":
          description: Успешное получение формы для смены пароля
          content:
            text/html:
              schema:
                type: string
        "401":
          description: Пользователь не авторизован
    post:
      description: Смена пароля авторизованного пользователя
      operationId: lokir.changePassword
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ChangePasswordForm"
      responses:
        "200":
          description: Успешная смена пароля
        "400":
          description: Неверный текущий пароль
        "401":
          description: Пользователь не авторизован
  /refresh:
    post:
      operationId: lokir.refreshToken
      responses:
        "302":
          description: Токен успешно обновлен
        "401":
          description: refresh токен истек
  /driver_login:
    post:
      description: Авторизация водителя
      operationId: lokir.driverAuthorization
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/LoginForm"
      responses:
        "302":
          description: Успешная авторизация
        "400":
          description: Неверный формат данных
        "401":
          description: Неверный пароль
        "404":
          description: Водитель не найден
    get:
      description: Сервер возвращает HTML форму для авторизации
      operationId: lokir.driverAuthorizationForm
      responses:
        "200":
          description: Форма для авторизации возвращена
          content:
            text/html:
              schema:
                type: string
  /passage:
    get:
      description: Информация о поездке
      operationId: lokir.driverPassage
      responses:
        "200":
          description: Получены актуальные данные о поездке
        "401":
          description: Водитель не авторизован
    post:
      description: Выполняет поиск заказов, начало и завершение поездок.
      responses:
        "200":
          description: Переход на следующий этап поездки
        "400":
          description: Неверный формат данных или нет доступных заказов
        "401":
          description: Водитель не авторизован
  /driver_account:
    get:
      description: Получение информации об аккаунте авторизованного водителя
      operationId: lokir.driverAccount
      responses:
        "200":
          description: Успешное получение информации об аккаунте
          content:
            text/html:
              schema:
                type: string
        "401":
          description: Водитель не авторизован
  /add_card:
    post:
      description: Добавление карты клиентом
      operationId: lokir.add_card
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CardForm"
      responses:
        "200":
          description: Карта успешно добавлена
        "400":
          description: Неверный формат данных
    get:
      description: Сервер возвращает HTML форму для добавления карты
      operationId: lokir.get_add_card
      responses:
        "200":
          description: Форма для добавления карты возвращена
          content:
            text/html:
              schema:
                type: string
        "401":
          description: Пользователь не авторизован
  /select_card:
    post:
      description: Выбор карты клиентом для оплаты заказа
      operationId: lokir.select_card
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/SelectCardForm"
      responses:
        "302":
          description: Карта успешно выбрана
        "400":
          description: Неверный формат данных
    get:
      description: Сервер возвращает HTML форму для выбора карты
      operationId: lokir.get_select_card
      responses:
        "200":
          description: Форма для выбора карты возвращена
          content:
            text/html:
              schema:
                type: string
        "401":
          description: Пользователь не авторизован
